### ISSUE TITLE
Connect to image repository (Google drive)

### ISSUE THREAD

**Issue by ktran4528** [COMP231-W23-Group5-TripBuddy/TripBuddy#11]

**Comment by paneleon** [comment]
After researching I found another service provider that is better suitable for the needs of the application and much easier to work with: ImageKit. 

Please refer to the documentation:
https://docs.imagekit.io/getting-started/quickstart-guides/react
https://docs.imagekit.io/media-library/overview/upload-files
https://www.npmjs.com/package/imagekitio-react

**Comment by paneleon** [comment]
authentication functionality required to finish the setup #13
