### ISSUE TITLE
As an IT manager, I want to manage Frequently asked questions, so that I can add new answers, update and delete questions

### ISSUE THREAD

**Issue by ktran4528** [COMP231-W23-Group5-TripBuddy/TripBuddy#177]
- [x] #178
- [x] #179
- [x] #180
- [x] #181
- [x] #182
- [x] #183
- [x] #184
- [x] #185
- [x] #186
- [x] #187

**Comment by paneleon** [comment]
@ktran4528 all tasks were completed, we can close the user story
