### ISSUE TITLE
As a tourist, I want to be able to visit home page, so that I can view my notifications, suggestions, checklist and have access to the application

### ISSUE THREAD

**Issue by ktran4528** [COMP231-W23-Group5-TripBuddy/TripBuddy#198]
- [x] #199
- [x] #200
- [x] #201
- [x] #202
- [x] #203
- [x] #204
- [x] #205
- [x] #206
- [x] #207
- [x] #208
- [x] #209
- [x] #210
- [x] #211
- [x] #212
- [x] #213
- [x] #214
- [x] #215

**Comment by paneleon** [comment]
@ktran4528 user story is completed
