### ISSUE TITLE
As a tourist, I want to be able to view and delete my saved post

### ISSUE THREAD

**Issue by ktran4528** [COMP231-W23-Group5-TripBuddy/TripBuddy#2]
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #107
- [x] #108
- [x] #126
- [x] #127
- [x] #128

**Comment by paneleon** [comment]
@ktran4528 can we also have a task to save a post (create an API and button on frontend as separate tasks)

**Comment by paneleon** [comment]
@ktran4528 all tasks are completed, please review
