### ISSUE TITLE
As a tourist, I want to access settings so that I can modify user profile information, payment methods and subscriptions 

### ISSUE THREAD

**Issue by ktran4528** [COMP231-W23-Group5-TripBuddy/TripBuddy#41]
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47
- [x] #48
- [x] #49
- [x] #50
- [x] #51
- [x] #52
- [x] #53
- [x] #54
- [x] #55
- [x] #56
- [x] #57
- [x] #58
- [x] #59
- [x] #60
- [x] #154
- [x] #155
- [x] #156
- [x] #157
- [x] #158
- [x] #159
- [x] #160
- [x] #161
- [x] #162

**Comment by paneleon** [comment]
@ktran4528 can you please add tasks to connect APIs to the views? I will take on those
