### ISSUE TITLE
As a tourist, I want to create new post with image, description and reviews, so that I can publish it 

### ISSUE THREAD

**Issue by ktran4528** [COMP231-W23-Group5-TripBuddy/TripBuddy#7]
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #20
- [x] #95
- [x] #98
- [x] #99
- [x] #106
- [x] #125

**Comment by paneleon** [comment]
All tasks are completed
